version: '3.4'

services:
  62bced2aff404a99afa3032b8fe953c5:
    image: 62bced2aff404a99afa3032b8fe953c5
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - alpha_vantage_api_key
    volumes:
      - .:/app
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678

secrets:
  alpha_vantage_api_key:
    file: ./secrets/alpha_vantage_api_key.txt
